spring.application.name=Optibase

# 1. Configuracion de conexion a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/optibase_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# 2. Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Puerto del servidor
server.port=8080

# 5. JWT
jwt.secret=optibase-clave-secreta-jwt-minimo-32-caracteres-2024
jwt.expiration=86400000